### ISSUE TITLE
リスト再生成時の情報消失時間の短縮

### ISSUE THREAD

**Issue by bee7813993** [shinta0806/YukaLister#194]
オフ会中にリスト再生成を行うと、生成中はファイル名検索だけしかできない。
そこで、
リスト生成のファイル名を
List.sqlite3_new
にして、生成完了したところで
・List.sqlite3_old があれば消す
・List.sqlite3 -> List.sqlite3_old
・List.sqlite3_new -> List.sqlite3
というようにリネームしてみたらどうでしょうか？

でも、ディスクを抜いた時の再生成は即時反映された方がいいとかあるかもしれない。。

**Comment by shinta0806** [comment]
ゆかりすたー NEBULA にて管理します。
https://github.com/shinta0806/YukaListerNebula/issues/87
